title: Settings
data:
  favicon: logo.png
  name: 'Active Matter'
  social_image: temp/social.png
  head_code: |-
    <!-- Fathom - beautiful, simple website analytics -->
    <script src="https://cdn.usefathom.com/script.js" data-site="RNGQUTET" defer></script>
    <!-- / Fathom -->