sections:
  main:
    display: Main
    fields:
      -
        handle: favicon
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          display: Favicon
          type: assets
          icon: assets
          listable: hidden
      -
        handle: name
        field:
          input_type: text
          antlers: false
          display: 'Site Name'
          type: text
          icon: text
          listable: hidden
      -
        handle: description
        field:
          input_type: text
          antlers: false
          display: 'Site description'
          type: textarea
          icon: text
          listable: hidden
      -
        handle: image
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Social image'
          type: assets
          icon: assets
          listable: hidden
      -
        handle: footer_text
        field:
          input_type: text
          antlers: false
          display: 'Footer Text'
          type: text
          icon: text
          listable: hidden
      -
        handle: head_code
        field:
          antlers: false
          display: 'Head Code'
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: foot_code
        field:
          antlers: false
          display: 'Footer Code'
          type: textarea
          icon: textarea
          listable: hidden
