sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: logo
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: cover_text
        field:
          antlers: false
          display: 'Cover Text'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: sections
        field:
          collapse: false
          previews: true
          sets:
            section:
              display: Section
              fields:
                -
                  handle: text
                  field:
                    collapse: false
                    always_show_set_button: false
                    previews: true
                    buttons:
                      - h5
                      - bold
                      - italic
                      - removeformat
                      - anchor
                    save_html: false
                    toolbar_mode: fixed
                    link_noopener: false
                    link_noreferrer: false
                    target_blank: false
                    reading_time: false
                    fullscreen: true
                    allow_source: true
                    enable_input_rules: true
                    enable_paste_rules: true
                    antlers: false
                    remove_empty_nodes: false
                    display: Text
                    type: bard
                    icon: bard
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
                -
                  handle: background
                  field:
                    mode: grid
                    container: assets
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    max_files: 1
                    display: Background
                    type: assets
                    icon: assets
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    always_save: false
          display: Sections
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: client
        field:
          input_type: text
          antlers: false
          display: Client
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
title: Project
